language: python
dist: xenial
python:
- 3.5
- 3.6
- 3.7
- 3.8
script: python -m unittest discover tests -t /
deploy:
  provider: pypi
  user: mdowds
  password:
    secure: hMHcNxxGsbGEXLm7q8wBAWE507idZstaxmoTFJUczBIs1YmLZerFfJnuot0aATtJ/sGoOHKwTB+YJDWDC6fXCpl82qNRw0GbHodwelN/VKVBVuRyHTx43r/tcvkjevrM3hRELuiZ422DlDvRGzc/MfCSFEo7ettlzoqTv52TEnw6mQoP2D0/GWemk0Gg6+6nOfuPW1Py8vSzxo6YNuE28o8u4CpepuFyvjIRHF2p68RqIbDpAyD94YXj5BbvKaXN0X8LBRuodOXYbGwN0FMHV0Y1Oa59v5V+H4hZgNbE2RsZD9ZtN9Hxi50B5ja20PQ3U3MOKOk7uhQ+VrHair6bWFk4EDp9Uq7M1QQJNsrHW8mkn666M3WtUy5t8ZZjPzhtEsIGT8jT3e3wGGYQLZOE+1Bwwm4EEr7x0Dayyo5/SWU/ns2ShN05Ljkf1CguCWif7RMfyM3wwu0Gl6cDCxLBfhu/NMN1gjKxISeHXpvec4F96ny5xKVwVer5Kzte0+6bZNRUfIqsM7Ve165GEJX2RKlNHPjE21U7hK07aE2gadKoIwXNxCFUVUs5F151F8Vd21xWrD3f093LMFDxUKF/0iUdiDsa8ZT1ZAfyws9/QNuN2CsOx2fYzUkeKkHtGYRFLKUodYBHH5G0o3OyxSY9AoLGQvbftUaiFhyaIShGQmU=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
